---
output: github_document
bibliography: [references.bib]
nocite: |
  @Spiegelman2005-Easy, @Williamson2013-Logbinomial
csl: aje.csl
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Easy R Code for Convergent Log-Linear Models

<!--can probably cite https://www.ncbi.nlm.nih.gov/pubmed/3509965 in the first sentence but need to read it to confirm-->
## Introduction
Reporting risk ratios instead of odds ratios is often preferable for interpretability. In a regression framework, risk ratios are most efficiently estimated through log-binomial generalized linear models; unfortunately, statistical software algorithms often fail to converge in the log-binomial setting @Williamson2013-Logbinomial. A previous publication in this journal introduced a SAS macro that can, in some settings, leverage parameter estimates from a modified Poisson regression to guide the log-binomial fitting algorithm towards convergence @Spiegelman2005-Easy. When this approach fails to fit a log-binomial model, parameter estimates from the modified Poisson regression are reported, though such estimates are known to exhibit reduced statistical efficiency.

Here, we present ... 

## Example

Example data, procedure, etc.

## References
